#!/bin/bash
check_user_exists() {
 if id "$1" &> /dev/null; then
   echo " user '$1' exists"
 else
   echo " user '$1' does not exists"
 fi
}

read -p "Enter you username: " name
check_user_exists "$name"
